data:
  label_path: data_preprocess/event_probability/no.62_Drd1-Cre.xlsx.day10_event.npy
  left_window_size: 50
  npy_path: data_preprocess/shuffle_neuron/no.62_Drd1-Cre.xlsx.day10_shuffle.npy
  right_window_size: 49
device: cuda
experiment: no.62_Drd1-Cre.xlsx.day10
output:
  dir_path: ./results-shuffle-average_precision
training:
  batch_size: 32
  hidden_dim: 64
  learning_rate: 0.0001
  num_folds: 5
  task_type: regression
  total_epochs: 300
