data:
  label_path: data_preprocess/event_probability_with_direction/no.62_Drd1-Cre.xlsx.day2_dir_event.npy
  left_window_size: 50
  npy_path: data_preprocess/npy/no.62_Drd1-Cre.xlsx.day2.neuron.npy
  right_window_size: 49
device: cuda
experiment: no.62_Drd1-Cre.xlsx.day2
output:
  dir_path: ./results-event-with-direction-ap/
training:
  batch_size: 32
  hidden_dim: 64
  learning_rate: 0.0001
  num_folds: 5
  task_type: regression
  total_epochs: 300
